vim.wo.number = true  -- Enables Line number --
vim.o.relativenumber = true  -- Enables Relative Line Number
vim.o.wrap = true -- Displays line as one long line (default: true)
vim.o.clipboard = 'unnamedplus' -- Sync clipboard between Neovim and Linux
vim.o.autoindent = true -- Enables Auto-indent (default: true)
vim.o.linebreak = true -- Companion to wrap
vim.o.mouse = 'a' -- Enable mouse mode (default: '')
vim.o.ignorecase = true 
vim.o.smartcase = true -- Smart Case (deafult: false)
vim.o.shiftwidth = 4 -- The number of spaces inserted for each indentation (default: 8)
vim.o.tabstop = 4 -- Insert n spaces for a tab (default: 8)
vim.o.softtabstop = 4 -- Number of spaces that a tab counts for while performing editing operations (default: 0)
vim.o.expandtab = true -- Convert tabs to spaces (default: false)
vim.o.scrolloff = 4 -- Minimal number of screen lines to keep above and below the cursor (default: 0)
vim.o.sidescrolloff = 8 -- Minimal number of screen columns either side of cursor if wrap is `false` (default: 0)
vim.o.cursorline = false -- Highlights the current line (default: false)
vim.o.splitbelow = true -- Force all horizontal splits to go below current window (default: false)
vim.o.splitright = true -- Force all vertical splits to go to the right of current window (default: false)
vim.o.numberwidth = 4 -- Set number column width to 4 (default: 4)
vim.o.breakindent = true -- Enable break indent (default: false)
vim.o.updatetime = 250 -- Decrease update time (default: 4000)
